config/routes.rb
Rails.application.routes.draw do
  resources :apis
  authenticated :user, ->(user) { user.admin? } do
    get 'admin', to: 'admin#index'
    get 'admin/books'
    get 'admin/users'
    get 'admin/show_book/:id', to: "admin#show_book", as: 'admin_book'
  end
  get 'search', to: 'search#index'
  get 'users/profile'
  devise_for :users, controllers: {
    sessions: 'users/sessions',
    registrations: 'users/registrations'
  }
  get '/u/:id', to: 'users#profile', as: 'user'
  resources :books do
  end
  #get 'static_page/home'
  root to: 'static_page#home'
  #get 'static_page/books'
  get '/books', to: 'static_page#books'
  #get 'static_page/about'
  get '/about', to: 'static_page#about'
  #get 'static_page/contact'
  get '/contact', to: 'static_page#contact' 
  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html

  # Defines the root path route ("/")
  # root "articles#index"
end

app/models/api.rb
class Api < ApplicationRecord
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  primary_abstract_class
end

app/models/book.rb
class Book < ApplicationRecord
    validates :title, :author, :description, presence: true, length: {minimum: 3}
    belongs_to :user

    has_rich_text :description
    has_one :content, class_name: 'ActionText::RichText', as: :record, dependent: :destroy

end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable

  has_many :books

  enum role: [:user, :admin]
  after_initialize :set_default_role, if: :new_record?

  private

  def set_default_role
    self.role ||= :user
  end
end

app/models/view.rb
class View < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable
end

app/controllers/admin_controller.rb
class AdminController < ApplicationController
  def index
  end

  def books
    @books = Book.all.includes(:user)
  end

  def users
  end

  def show_book
    @book = Book.includes(:user).find(params[:id])
  end
end

app/controllers/apis_controller.rb
class ApisController < ApplicationController
  before_action :set_api, only: %i[ show edit update destroy ]

  # GET /apis or /apis.json
  def index
    @apis = Api.all
  end

  # GET /apis/1 or /apis/1.json
  def show
  end

  # GET /apis/new
  def new
    @api = Api.new
  end

  # GET /apis/1/edit
  def edit
  end

  # POST /apis or /apis.json
  def create
    @api = Api.new(api_params)

    respond_to do |format|
      if @api.save
        format.html { redirect_to api_url(@api), notice: "Api was successfully created." }
        format.json { render :show, status: :created, location: @api }
      else
        format.html { render :new, status: :unprocessable_entity }
        format.json { render json: @api.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /apis/1 or /apis/1.json
  def update
    respond_to do |format|
      if @api.update(api_params)
        format.html { redirect_to api_url(@api), notice: "Api was successfully updated." }
        format.json { render :show, status: :ok, location: @api }
      else
        format.html { render :edit, status: :unprocessable_entity }
        format.json { render json: @api.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /apis/1 or /apis/1.json
  def destroy
    @api.destroy

    respond_to do |format|
      format.html { redirect_to apis_url, notice: "Api was successfully destroyed." }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_api
      @api = Api.find(params[:id])
    end

    # Only allow a list of trusted parameters through.
    def api_params
      params.require(:api).permit(:api)
    end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
    before_action :set_query

    def set_query
        @query = Book.ransack(params[:q])
    end
end

app/controllers/books_controller.rb
class BooksController < ApplicationController
  before_action :set_book, only: %i[ show edit update destroy ]
  before_action :authenticate_user!, except: %i[show index]
  
  # GET /books or /books.json
  def index
    @books = Book.all.order(created_at: :desc)
  end

  # GET /books/1 or /books/1.json
  def show
    @book.update(views: @book.views + 1)
  end


  # GET /books/new
  def new
    @book = Book.new
  end

  # GET /books/1/edit
  def edit
  end

  # POST /books or /books.json
  def create
    @book = Book.new(book_params)
    @book.user = current_user

    respond_to do |format|
      if @book.save
        format.html { redirect_to book_url(@book), notice: "Book was successfully created." }
        format.json { render :show, status: :created, location: @book }
      else
        format.html { render :new, status: :unprocessable_entity }
        format.json { render json: @book.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /books/1 or /books/1.json
  def update
    respond_to do |format|
      if @book.update(book_params)
        format.html { redirect_to book_url(@book), notice: "Book was successfully updated." }
        format.json { render :show, status: :ok, location: @book }
      else
        format.html { render :edit, status: :unprocessable_entity }
        format.json { render json: @book.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /books/1 or /books/1.json
  def destroy
    @book.destroy

    respond_to do |format|
      format.html { redirect_to books_url, notice: "Book was successfully destroyed." }
      format.json { head :no_content }
    end
  end



  private
    # Use callbacks to share common setup or constraints between actions.
    def set_book
      @book = Book.find(params[:id])
    end

    # Only allow a list of trusted parameters through.
    def book_params
      params.require(:book).permit(:title, :author, :description)
    end
end

app/controllers/search_controller.rb
class SearchController < ApplicationController
  def index
    @query = Book.ransack(params[:q])
    @posts = @query.result(distinct: true)
  end
end

app/controllers/static_page_controller.rb
class StaticPageController < ApplicationController
  def home
    @dog_fact = JSON.parse(HTTParty.get("https://dog-api.kinduff.com/api/facts?number=1").body)
  end

  def books
  end

  def about
    @a_biblia_digital = JSON.parse(HTTParty.get("https://www.abibliadigital.com.br/api/verses/nvi/random").body)
  end

  def contact
  end
end

app/controllers/users/sessions_controller.rb
# frozen_string_literal: true

class Users::SessionsController < Devise::SessionsController
  # before_action :configure_sign_in_params, only: [:create]

  # GET /resource/sign_in
  # def new
  #   super
  # end

  # POST /resource/sign_in
  # def create
  #   super
  # end

  # DELETE /resource/sign_out
  # def destroy
  #   super
  # end

  # protected

  # If you have extra params to permit, append them to the sanitizer.
  # def configure_sign_in_params
  #   devise_parameter_sanitizer.permit(:sign_in, keys: [:attribute])
  # end
end

app/controllers/users/unlocks_controller.rb
# frozen_string_literal: true

class Users::UnlocksController < Devise::UnlocksController
  # GET /resource/unlock/new
  # def new
  #   super
  # end

  # POST /resource/unlock
  # def create
  #   super
  # end

  # GET /resource/unlock?unlock_token=abcdef
  # def show
  #   super
  # end

  # protected

  # The path used after sending unlock password instructions
  # def after_sending_unlock_instructions_path_for(resource)
  #   super(resource)
  # end

  # The path used after unlocking the resource
  # def after_unlock_path_for(resource)
  #   super(resource)
  # end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  before_action :set_user
  def profile
    @user.update(views: @user.views + 1)
  end

  private

  def set_user
    @user = User.find(params[:id])
  end
end

app/helpers/admin_helper.rb
module AdminHelper
end

app/helpers/api_helper.rb
module ApiHelper
end

app/helpers/apis_helper.rb
module ApisHelper
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/books_helper.rb
module BooksHelper
end

app/helpers/search_helper.rb
module SearchHelper
end

app/helpers/static_page_helper.rb
module StaticPageHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/search/_form.html.erb
<%= search_form_for(@query, url: search_path, method: :get, class:'d-flex') do |f| %>
    <%= f.search_field :title_or_author_cont_any,
     placeholder: "Search...",
     class: "form-control me-2" %>
    <% f.submit "Search!", class:"btn btn-outline-success" %>
<% end %>

app/views/search/index.html.erb
<h1 class="text-center"><%= pluralize(@posts.count, "Book") %> </h1>
<%= render 'search/form' %>
<div class="container">
    <table class= "table table-dark table-striped">
    <thead>
     <tr>
        <th><%= sort_link(@query, :title, "Title", default_order: :asc) %></th>
        <th><%= sort_link(@query, :body, "Description") %></th>
        <th><%= sort_link(@query, :author, "Author") %></th>
     </tr>
    </thead>

    <tbody>
        <% @posts.each do |book| %>
    <tr>
        <td><%= link_to book.title, book%></td>
        <td><%= book.description.to_plain_text.truncate_words(25)%></td>
        <td><%= link_to book.author, book%></td>
    </tr>
    <% end %>
    </tbody>
    </table>
</div>

app/views/static_page/_about.html.erb
<div class="p-5 text-center bg-image rounded-3">
  <div class="mask" style="background-color: rgba(255, 255, 255, 0.6);">
    <div class="d-flex justify-content-center align-items-center h-100">
      <div class="text-black">
        <h1 class="mb-3">About us</h1>
        <h4 class="mb-3">This is a book library to demonstrate the various features of Ruby on rails for cloud application development project<br>
        This application was developed by Robertas Kuchtovas - x20124287<br>
        Please visit the contact page if you have any more questions</h4>
        <a class="btn btn-outline-light btn-lg text-black" href="contact" role="button">Contact us</a>
        <h4 class="mb-3">Here is a random verse from the bible below please enjoy.<br>
        It is written in portugese!</h4>
        <h5><% @a_biblia_digital.each do |verse| %>
    <p><%= verse %></p></h5>
    <% end %>
      </div>
    </div>
  </div>
</div>

app/views/static_page/about.html.erb
<%= render 'static_page/about' %>

app/views/static_page/books.html.erb
<h1>StaticPage#books</h1>
<p>Find me in app/views/static_page/books.html.erb</p>

app/views/static_page/contact.html.erb
<form enctype="multipart/form-data" method="post" action="https://www.freedback.com/mail.php" accept-charset="UTF-8">
<div>
<input type="hidden" name="acctid" id="acctid" value="2bhfgwl7iuile0fo" />
<input type="hidden" name="formid" id="formid" value="2004404" />
<input type="hidden" name="required_vars" id="required_vars" value="name,email,field-message" />
</div>
<table cellspacing="5" cellpadding="5" border="0">
<tr>
<td valign="top">
<strong>Name:</strong>
</td>
<td valign="top">
<input type="text" name="name" id="name" size="40" value="" />

</td>
</tr>
<tr>
<td valign="top">
<strong>Email Address:</strong>
</td>
<td valign="top">
<input type="text" name="email" id="email" size="40" value="" />

</td>
</tr>
<tr>
<td valign="top">
<strong>Message:</strong>
</td>
<td valign="top">
<textarea name="field-message" id="field-message" rows="6" cols="40"></textarea>

</td>
</tr>
<tr>
<td colspan="2" align="center">
<input type="submit" value=" Submit Form " />
</td>
</tr>
</table>
</form>

app/views/static_page/home.html.erb
<div class = "container">
    <h1>Cloud Library</h1>
    <p>Take a look at the books tab!</p>
    <%= link_to "About us", about_path, class: "btn btn-secondary" %>
    <%= link_to "Contact Us", contact_path, class: "btn btn-primary" %>
    <p class="text-center"><h2>Enjoy a random dog fact on us!</h2>
    <% @dog_fact.each do |facts| %>
    <%= facts %></p>
    <% end %>
</div>