config/routes.rb
Rails.application.routes.draw do
  resources :apis
  authenticated :user, ->(user) { user.admin? } do
    get 'admin', to: 'admin#index'
    get 'admin/books'
    get 'admin/users'
    get 'admin/show_book/:id', to: "admin#show_book", as: 'admin_book'
  end
  get 'search', to: 'search#index'
  get 'users/profile'
  devise_for :users, controllers: {
    sessions: 'users/sessions',
    registrations: 'users/registrations'
  }
  get '/u/:id', to: 'users#profile', as: 'user'
  resources :books do
  end
  #get 'static_page/home'
  root to: 'static_page#home'
  #get 'static_page/books'
  get '/books', to: 'static_page#books'
  #get 'static_page/about'
  get '/about', to: 'static_page#about'
  #get 'static_page/contact'
  get '/contact', to: 'static_page#contact' 
  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html

  # Defines the root path route ("/")
  # root "articles#index"
end

app/models/api.rb
class Api < ApplicationRecord
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  primary_abstract_class
end

app/models/book.rb
class Book < ApplicationRecord
    validates :title, :author, :description, presence: true, length: {minimum: 3}
    belongs_to :user

    has_rich_text :description
    has_one :content, class_name: 'ActionText::RichText', as: :record, dependent: :destroy

end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable

  has_many :books

  enum role: [:user, :admin]
  after_initialize :set_default_role, if: :new_record?

  private

  def set_default_role
    self.role ||= :user
  end
end

app/models/view.rb
class View < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable
end

app/controllers/admin_controller.rb
class AdminController < ApplicationController
  def index
  end

  def books
    @books = Book.all.includes(:user)
  end

  def users
  end

  def show_book
    @book = Book.includes(:user).find(params[:id])
  end
end

app/controllers/apis_controller.rb
class ApisController < ApplicationController
  before_action :set_api, only: %i[ show edit update destroy ]

  # GET /apis or /apis.json
  def index
    @apis = Api.all
  end

  # GET /apis/1 or /apis/1.json
  def show
  end

  # GET /apis/new
  def new
    @api = Api.new
  end

  # GET /apis/1/edit
  def edit
  end

  # POST /apis or /apis.json
  def create
    @api = Api.new(api_params)

    respond_to do |format|
      if @api.save
        format.html { redirect_to api_url(@api), notice: "Api was successfully created." }
        format.json { render :show, status: :created, location: @api }
      else
        format.html { render :new, status: :unprocessable_entity }
        format.json { render json: @api.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /apis/1 or /apis/1.json
  def update
    respond_to do |format|
      if @api.update(api_params)
        format.html { redirect_to api_url(@api), notice: "Api was successfully updated." }
        format.json { render :show, status: :ok, location: @api }
      else
        format.html { render :edit, status: :unprocessable_entity }
        format.json { render json: @api.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /apis/1 or /apis/1.json
  def destroy
    @api.destroy

    respond_to do |format|
      format.html { redirect_to apis_url, notice: "Api was successfully destroyed." }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_api
      @api = Api.find(params[:id])
    end

    # Only allow a list of trusted parameters through.
    def api_params
      params.require(:api).permit(:api)
    end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
    before_action :set_query

    def set_query
        @query = Book.ransack(params[:q])
    end
end

app/controllers/books_controller.rb
class BooksController < ApplicationController
  before_action :set_book, only: %i[ show edit update destroy ]
  before_action :authenticate_user!, except: %i[show index]
  
  # GET /books or /books.json
  def index
    @books = Book.all.order(created_at: :desc)
  end

  # GET /books/1 or /books/1.json
  def show
    @book.update(views: @book.views + 1)
  end


  # GET /books/new
  def new
    @book = Book.new
  end

  # GET /books/1/edit
  def edit
  end

  # POST /books or /books.json
  def create
    @book = Book.new(book_params)
    @book.user = current_user

    respond_to do |format|
      if @book.save
        format.html { redirect_to book_url(@book), notice: "Book was successfully created." }
        format.json { render :show, status: :created, location: @book }
      else
        format.html { render :new, status: :unprocessable_entity }
        format.json { render json: @book.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /books/1 or /books/1.json
  def update
    respond_to do |format|
      if @book.update(book_params)
        format.html { redirect_to book_url(@book), notice: "Book was successfully updated." }
        format.json { render :show, status: :ok, location: @book }
      else
        format.html { render :edit, status: :unprocessable_entity }
        format.json { render json: @book.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /books/1 or /books/1.json
  def destroy
    @book.destroy

    respond_to do |format|
      format.html { redirect_to books_url, notice: "Book was successfully destroyed." }
      format.json { head :no_content }
    end
  end



  private
    # Use callbacks to share common setup or constraints between actions.
    def set_book
      @book = Book.find(params[:id])
    end

    # Only allow a list of trusted parameters through.
    def book_params
      params.require(:book).permit(:title, :author, :description)
    end
end

app/controllers/search_controller.rb
class SearchController < ApplicationController
  def index
    @query = Book.ransack(params[:q])
    @posts = @query.result(distinct: true)
  end
end

app/controllers/static_page_controller.rb
class StaticPageController < ApplicationController
  def home
    @dog_fact = JSON.parse(HTTParty.get("https://dog-api.kinduff.com/api/facts?number=1").body)
  end

  def books
  end

  def about
    @a_biblia_digital = JSON.parse(HTTParty.get("https://www.abibliadigital.com.br/api/verses/nvi/random").body)
  end

  def contact
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  before_action :set_user
  def profile
    @user.update(views: @user.views + 1)
  end

  private

  def set_user
    @user = User.find(params[:id])
  end
end

app/helpers/admin_helper.rb
module AdminHelper
end

app/helpers/api_helper.rb
module ApiHelper
end

app/helpers/apis_helper.rb
module ApisHelper
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/books_helper.rb
module BooksHelper
end

app/helpers/search_helper.rb
module SearchHelper
end

app/helpers/static_page_helper.rb
module StaticPageHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/active_storage/blobs/_blob.html.erb
<figure class="attachment attachment--<%= blob.representable? ? "preview" : "file" %> attachment--<%= blob.filename.extension %>">
  <% if blob.representable? %>
    <%= image_tag blob.representation(resize_to_limit: local_assigns[:in_gallery] ? [ 800, 600 ] : [ 1024, 768 ]) %>
  <% end %>

  <figcaption class="attachment__caption">
    <% if caption = blob.try(:caption) %>
      <%= caption %>
    <% else %>
      <span class="attachment__name"><%= blob.filename %></span>
      <span class="attachment__size"><%= number_to_human_size blob.byte_size %></span>
    <% end %>
  </figcaption>
</figure>

app/views/admin/_link.html.erb
<%= link_to resource.name.capitalize, url_for([:admin, resource]), class:'btn btn-primary' %>

app/views/admin/_nav_links.html.erb
<div class= "container text-center">
    <p>
    <%= link_to "Admin", admin_path %><%= " > #{params[:action].capitalize}" unless params[:action].eql?("index")%>
    </p>
    <div class="btn-group">
    <%= render "admin/link", resource: Book %>
    <%= render "admin/link", resource: User %>
</div>

app/views/admin/books.html.erb
<div class="container">
    <h1 class="text-center">Administrator</h1>
    <%= render 'admin/nav_links' %>
      <table class="table table-dark table-striped">
        <thead>
          <tr>
                <th scope="col">Id</th>
                <th scope="col">Book</th>
                <th scope="col">Title</th>
          </tr>
        </thead>
        <tbody>
            <% @books.each do |book| %>
            <tr>
                <th scope="row"><%= book.id %></th>
                <td><%= link_to book.title.truncate(15), admin_book_path(book) %></td>
                <td><%= book.user.name %></td>
            </tr>
            <% end %>
            </tbody>
       </table>

</div>

app/views/admin/index.html.erb
<div class="container">
    <h1 class="text-center">Administrator</h1>
    <%= render 'admin/nav_links' %>

app/views/admin/show_book.html.erb
<div class="container">
    <h1 class="text-center">Administrator</h1>
    <%= render 'admin/nav_links' %>
    <div class="text-center mt-5">
      <div class="btn-group">
        <%= link_to "Edit", edit_book_path(@book), class:"btn btn-warning" %>
        <%= button_to "Delete", @book, method: :delete, data: { confirm: "Are you sure?" }, class:"btn btn-danger" %>
        </div>
    </div>
<div class="row mt-1">
    <p>
        <strong>Views:</strong> <%= @book.views %>
    </p>
</div>
    <div class="row mt-1">
      <p>
        <strong>Title:</strong> <%= @book.title %>
      </p>
    </div>
<div class= "row mt-1">
    <p>
    <strong>Author:</strong> <%= @book.author %>
    </p>
</div>
<div class= "row mt-1">
    <p>
    <strong>Description:</strong> <%= @book.description %>
    </p>
</div>
<div class= "row mt-1">
    <p><strong>User:</strong>
    <%= "#{@book.user.email} | #{@book.user.name} | #{pluralize(@book.user.views, "View")}"%>
    </p>
</div>
</div>

app/views/admin/users.html.erb
<div class="container">
    <h1 class="text-center">Administrator</h1>
    <%= render 'admin/nav_links' %>

app/views/layouts/_alerts.html.erb
<% if notice || alert %>
    <p class="notice"><%= notice %> </p>
<% elsif alert %>
    <p class="alert"><%= alert %> </p>
<% end %>

app/views/layouts/_navbar.html.erb
<nav class="navbar navbar-expand-lg bg-light">
  <div class="container-fluid">
    <%= link_to "Cloud Library", root_path, class: 'navbar-brand' %>
    <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
      <span class="navbar-toggler-icon"></span>
    </button>
    <div class="collapse navbar-collapse" id="navbarSupportedContent">
      <ul class="navbar-nav me-auto mb-2 mb-lg-0">
        <li class="nav-item">
        <%= link_to "Home", root_path, class: 'nav-link' %>
        </li>
        <li class="nav-item">
        <%= link_to "Books", books_path, class: 'nav-link' %>
        </li>
        <li class="nav-item">
        <%= link_to "About", about_path, class: 'nav-link' %>
        </li>
        <li class="nav-item">
        <%= link_to "Contact Us", contact_path, class: 'nav-link' %>
        </li>
      </ul>
      <ul>
      <ul class="navbar-nav">
      <%= render 'search/form'%>
      <%= render 'user/session_manager' %>
      </ul>
    </div>
  </div>
</nav>

app/views/layouts/action_text/contents/_content.html.erb
<div class="trix-content">
  <%= yield -%>
</div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>CadbookshopFinal</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.0.2/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-EVSTQN3/azprG1Anm3QDgpJLIm9Nao0Yz1ztcQTwFspd3yD65VohhpuuCOmLASjC" crossorigin="anonymous">
    <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.0.2/dist/js/bootstrap.bundle.min.js" integrity="sha384-MrcW6ZMFYlzcLA8Nl+NtUVF0sA7MsXsP1UyJoMp4YLEuNSfAP+JcXn/tWtIaxVXM" crossorigin="anonymous"></script>
    <%= stylesheet_link_tag "application", "data-turbo-track": "reload" %>
    <%= javascript_tag %>
  </head>
  <body>
    <header>
  <%= render 'layouts/navbar' %>
  <%= render 'layouts/alerts' %>
    </header>
    <main>
    <%= yield %>
    </main>
  </body>
</html>