config/routes.rb
Rails.application.routes.draw do
  resources :apis
  authenticated :user, ->(user) { user.admin? } do
    get 'admin', to: 'admin#index'
    get 'admin/books'
    get 'admin/users'
    get 'admin/show_book/:id', to: "admin#show_book", as: 'admin_book'
  end
  get 'search', to: 'search#index'
  get 'users/profile'
  devise_for :users, controllers: {
    sessions: 'users/sessions',
    registrations: 'users/registrations'
  }
  get '/u/:id', to: 'users#profile', as: 'user'
  resources :books do
  end
  #get 'static_page/home'
  root to: 'static_page#home'
  #get 'static_page/books'
  get '/books', to: 'static_page#books'
  #get 'static_page/about'
  get '/about', to: 'static_page#about'
  #get 'static_page/contact'
  get '/contact', to: 'static_page#contact' 
  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html

  # Defines the root path route ("/")
  # root "articles#index"
end

app/models/book.rb
class Book < ApplicationRecord
    validates :title, :author, :description, presence: true, length: {minimum: 3}
    belongs_to :user

    has_rich_text :description
    has_one :content, class_name: 'ActionText::RichText', as: :record, dependent: :destroy

end

app/controllers/books_controller.rb
class BooksController < ApplicationController
  before_action :set_book, only: %i[ show edit update destroy ]
  before_action :authenticate_user!, except: %i[show index]
  
  # GET /books or /books.json
  def index
    @books = Book.all.order(created_at: :desc)
  end

  # GET /books/1 or /books/1.json
  def show
    @book.update(views: @book.views + 1)
  end


  # GET /books/new
  def new
    @book = Book.new
  end

  # GET /books/1/edit
  def edit
  end

  # POST /books or /books.json
  def create
    @book = Book.new(book_params)
    @book.user = current_user

    respond_to do |format|
      if @book.save
        format.html { redirect_to book_url(@book), notice: "Book was successfully created." }
        format.json { render :show, status: :created, location: @book }
      else
        format.html { render :new, status: :unprocessable_entity }
        format.json { render json: @book.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /books/1 or /books/1.json
  def update
    respond_to do |format|
      if @book.update(book_params)
        format.html { redirect_to book_url(@book), notice: "Book was successfully updated." }
        format.json { render :show, status: :ok, location: @book }
      else
        format.html { render :edit, status: :unprocessable_entity }
        format.json { render json: @book.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /books/1 or /books/1.json
  def destroy
    @book.destroy

    respond_to do |format|
      format.html { redirect_to books_url, notice: "Book was successfully destroyed." }
      format.json { head :no_content }
    end
  end



  private
    # Use callbacks to share common setup or constraints between actions.
    def set_book
      @book = Book.find(params[:id])
    end

    # Only allow a list of trusted parameters through.
    def book_params
      params.require(:book).permit(:title, :author, :description)
    end
end

app/helpers/books_helper.rb
module BooksHelper
end

app/views/books/_book.html.erb
<% if current_user %>
<div id="<%= dom_id book %>">

    <h2><%= book.title %></h2>
    <h4>Added by <%= link_to book.user.name, user_path(book.user) %></h4>
    <h5><%= book.author %></h5>
<div>
    <%= book.description %>
    <%= pluralize(book.views, "view") %>
</div>
</div>

<% end %>

app/views/books/_form.html.erb
<%= form_with(model: book) do |form| %>
  <% if book.errors.any? %>
    <div style="color: red">
      <h2><%= pluralize(book.errors.count, "error") %> prohibited this book from being saved:</h2>

      <ul>
        <% book.errors.each do |error| %>
          <li><%= error.full_message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <div>
    <%= form.label :title, style: "display: block" %>
    <%= form.text_area :title %>
  </div>

  <div>
    <%= form.label :author, style: "display: block" %>
    <%= form.text_field :author %>
  </div>

  <div>
    <%= form.label :description, style: "display: block" %>
    <%= form.rich_text_area :description %>
  </div>

  <div>
    <%= form.submit %>
  </div>
<% end %>

app/views/books/edit.html.erb
<div class = "container">
<h1>Edit book</h1>

<%= render "form", book: @book %>

<br>

<div>
  <%= link_to "Show this book", @book %> |
  <%= link_to "Back to books", books_path %>
</div>
</div>

app/views/books/index.html.erb
<% if current_user %>
<p style="color: green"><%= notice %></p>
<div class = "container">
<h1>Books</h1>

<div id="books">
  <% @books.each do |book| %>
    <%= render book %>
    <p>
      <%= link_to "Show this book", book %>
    </p>
  <% end %>
</div>

<%= link_to "New book", new_book_path %>
</div>
<% end %>

app/views/books/new.html.erb
<% if current_user %>
<div class = "container">
<h1>New book</h1>

<%= render "form", book: @book  if current_user.admin?%>

<br>

<div>
  <%= link_to "Back to books", books_path %>
</div>
</div>
<% end %>

app/views/books/show.html.erb
<% if current_user %>
<p style="color: green"><%= notice %></p>
<div class="container">
<%= render @book %>

<div>
<%= link_to "Edit this book", edit_book_path(@book) if current_user.admin? %>
  <%= link_to "Back to books", books_path %>

  <%= button_to "Destroy this book", @book, method: :delete if current_user.admin? %>

</div>
</div>
<% end %>