config/routes.rb
Rails.application.routes.draw do
  resources :apis
  authenticated :user, ->(user) { user.admin? } do
    get 'admin', to: 'admin#index'
    get 'admin/books'
    get 'admin/users'
    get 'admin/show_book/:id', to: "admin#show_book", as: 'admin_book'
  end
  get 'search', to: 'search#index'
  get 'users/profile'
  devise_for :users, controllers: {
    sessions: 'users/sessions',
    registrations: 'users/registrations'
  }
  get '/u/:id', to: 'users#profile', as: 'user'
  resources :books do
  end
  #get 'static_page/home'
  root to: 'static_page#home'
  #get 'static_page/books'
  get '/books', to: 'static_page#books'
  #get 'static_page/about'
  get '/about', to: 'static_page#about'
  #get 'static_page/contact'
  get '/contact', to: 'static_page#contact' 
  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html

  # Defines the root path route ("/")
  # root "articles#index"
end

app/models/api.rb
class Api < ApplicationRecord
end

app/controllers/apis_controller.rb
class ApisController < ApplicationController
  before_action :set_api, only: %i[ show edit update destroy ]

  # GET /apis or /apis.json
  def index
    @apis = Api.all
  end

  # GET /apis/1 or /apis/1.json
  def show
  end

  # GET /apis/new
  def new
    @api = Api.new
  end

  # GET /apis/1/edit
  def edit
  end

  # POST /apis or /apis.json
  def create
    @api = Api.new(api_params)

    respond_to do |format|
      if @api.save
        format.html { redirect_to api_url(@api), notice: "Api was successfully created." }
        format.json { render :show, status: :created, location: @api }
      else
        format.html { render :new, status: :unprocessable_entity }
        format.json { render json: @api.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /apis/1 or /apis/1.json
  def update
    respond_to do |format|
      if @api.update(api_params)
        format.html { redirect_to api_url(@api), notice: "Api was successfully updated." }
        format.json { render :show, status: :ok, location: @api }
      else
        format.html { render :edit, status: :unprocessable_entity }
        format.json { render json: @api.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /apis/1 or /apis/1.json
  def destroy
    @api.destroy

    respond_to do |format|
      format.html { redirect_to apis_url, notice: "Api was successfully destroyed." }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_api
      @api = Api.find(params[:id])
    end

    # Only allow a list of trusted parameters through.
    def api_params
      params.require(:api).permit(:api)
    end
end

app/helpers/api_helper.rb
module ApiHelper
end

app/helpers/apis_helper.rb
module ApisHelper
end

app/views/apis/_api.html.erb
<div id="<%= dom_id api %>">
  <p>
    <strong>Api:</strong>
    <%= api.api %>
  </p>

</div>

app/views/apis/_form.html.erb
<%= form_with(model: api) do |form| %>
  <% if api.errors.any? %>
    <div style="color: red">
      <h2><%= pluralize(api.errors.count, "error") %> prohibited this api from being saved:</h2>

      <ul>
        <% api.errors.each do |error| %>
          <li><%= error.full_message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <div>
    <%= form.label :api, style: "display: block" %>
    <%= form.text_field :api %>
  </div>

  <div>
    <%= form.submit %>
  </div>
<% end %>

app/views/apis/edit.html.erb
<h1>Editing api</h1>

<%= render "form", api: @api %>

<br>

<div>
  <%= link_to "Show this api", @api %> |
  <%= link_to "Back to apis", apis_path %>
</div>

app/views/apis/index.html.erb
<p style="color: green"><%= notice %></p>

<h1>Apis</h1>

<div id="apis">
  <% @apis.each do |api| %>
    <%= render api %>
    <p>
      <%= link_to "Show this api", api %>
    </p>
  <% end %>
</div>

<%= link_to "New api", new_api_path %>

app/views/apis/new.html.erb
<h1>New api</h1>

<%= render "form", api: @api %>

<br>

<div>
  <%= link_to "Back to apis", apis_path %>
</div>

app/views/apis/show.html.erb
<p style="color: green"><%= notice %></p>

<%= render @api %>

<div>
  <%= link_to "Edit this api", edit_api_path(@api) %> |
  <%= link_to "Back to apis", apis_path %>

  <%= button_to "Destroy this api", @api, method: :delete %>
</div>